### ISSUE TITLE
Multiline text within an a box

### ISSUE THREAD

**Issue by avallark** [stathissideris/dali#13]
Thank you for the wonderful library! :)

I am trying to figure out how to render a long text in text wrapped way within a box. Is there a way to automatically do that?

**Comment by avallark** [comment]
closing this issue. I manually did the word-wrapping. I realised that wrapping isnt in SVG spec.

**Comment by stathissideris** [comment]
Yeah, it isn't in the spec, but maybe it could be emulated. It would be nice to have that, but it's not entirely trivial!
