### ISSUE TITLE
PNG as Buffer instead of writing to disk

### ISSUE THREAD

**Issue by alexandrepage** [stathissideris/dali#3]
Hi, I'm trying to generate a png without having to write it to disk. For example
`(def buffer-image (io/render-to-png document))`
So then I can do what I want with the image without having to write to disk first. 
Hope I'm clear, and by the way awesome librairy

**Comment by stathissideris** [comment]
I've looked around a bit, and it seems that Batik (which dali uses internally for rasterization) has no super-easy way to support this, but it there are a couple of hacks that can be employed to make this happen. I'll include it in the next version, watch this space! Glad you like the library :+1:
